[project]
name = "kafka-producer-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "kafka-python-ng>=2.2.3",
    "pydantic>=2.11.9",
    "python-dotenv>=1.1.1",
]
